version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1

jobs:
  build:
    docker:
      - image: python:3.11 # Use the desired Python version


    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_REGION: ${AWS_REGION}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          from: bucket
          to: s3://061bfde6edff55df/prefix
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: s3://061bfde6edff55df


      # Run the tests
      - run:
          name: Run Tests
          command: |
            python -m unittest test_area_calculator.py

workflows:
  s3-example:
    jobs:
      - build
